[default]
description = "Default permissions for the plugin"
permissions = [
  "allow-capture", 
  "allow-identify",
  "allow-alias",
  "allow-reset",
  "allow-get-distinct-id",
  "allow-get-config"
]

[[permission]]
identifier = "allow-capture"
description = "Allows capturing PostHog events"
commands.allow = ["capture"]

[[permission]]
identifier = "allow-identify" 
description = "Allows identifying users in PostHog"
commands.allow = ["identify"]

[[permission]]
identifier = "allow-alias"
description = "Allows creating user aliases in PostHog"
commands.allow = ["alias"]

[[permission]]
identifier = "allow-reset"
description = "Allows resetting user data in PostHog"
commands.allow = ["reset"]

[[permission]]
identifier = "allow-get-distinct-id"
description = "Allows getting the current distinct ID"
commands.allow = ["get_distinct_id"]


[[permission]]
identifier = "allow-get-config"
description = "Allows getting PostHog configuration for frontend initialization"
commands.allow = ["get_config"]
